-- Your SQL goes here

CREATE TABLE sub_tasks (
    id SERIAL PRIMARY KEY,
    task_id SERIAL NOT NULL REFERENCES tasks (id),
    title TEXT NOT NULL,
    done BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);