//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use super::sea_orm_active_enums::ClearanceMapping;
use async_graphql::*;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, SimpleObject)]
#[sea_orm(table_name = "timelines_users")]
#[graphql(name = "TimelineUser")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub timeline_id: i32,
    pub user_id: i32,
    pub relation: ClearanceMapping,
    #[sea_orm(column_type = "Text")]
    pub color: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::timelines::Entity",
        from = "Column::TimelineId",
        to = "super::timelines::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Timelines,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::timelines::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Timelines.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
